### PR TITLE
Add "at a glance" section to the README

### PR DESCRIPTION
**Pull request by Jutanium**
We've gotten the feedback that our README could use a code sample. This lets you quickly get a sense for what Solid looks like and what it feels to use.

### CODE REVIEW

**Comment by thetarnav** [comment]
lmao
when the code sample is so hidden you get PRs adding new ones

image

**Comment by Jutanium** [comment]
@thetarnav LOL
I'll remove that one

**Comment by Jutanium** [comment]
Actually, @thetarnav - they serve pretty different purposes. That later one is more explanatory - this one is short and sweet as a way to show what the framework looks like.

**Review by davedbase — APPROVED** [review]
Much cleaner. Very nice.

**Pull request merged**
