### PR TITLE
Expose Setter Type for createSignal

### LINKED ISSUE #507: Export a type for createSignal's setter
**IMPORTANT: If you have a question or an idea for a new feature use Github Discussions instead**

**Describe the bug**
The type of createSignal's setter is not exported anywhere. This was recently made more problematic due to [https://github.com/solidjs/solid/commit/2f5311dc90f25b8a68de536d7a095112235d385b](https://github.com/solidjs/solid/commit/2f5311dc90f25b8a68de536d7a095112235d385b) which changed the setter's type from a simple setter to one that also accepted a function form, making writing types, for example when passing a setter as a prop, more tedious. 

**To Reproduce**
N/A

**Expected behavior**
Export a setter equivalent of `Accessor<T>`.

**Reproduction**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by otonashixav**
Exposes the Setter<T> type without changes to existing tests. (closes #507)

### CODE REVIEW

**Comment by atk** [comment]
I'm not really happy about the casts to `any`, but at the moment, I don't see any other way.

**Comment by otonashixav** [comment]
Let me try to get rid of them, actually.

**Comment by atk** [comment]
Good job!

**Comment by ryansolid** [comment]
Yeah I think I'm pretty happy with this one. Thank you.

**Pull request merged**
