### PR TITLE
Typescript: disallow setting readonly store props

### PR DESCRIPTION
**Pull request by JorrenH**
## Summary

Resolves (part of) the issue posed in #1359. Limits store setters to non-readonly properties in the store. This fix only addresses usage of the store setter by path (`setStore("a", "b", value)`). Setting by object (`setStore({ a: { b: value }})`) cannot be checked without impact.

If we would type check setting by object, setters like `setStore("el", {} as Element)` would stop working because the `Element` interface contains readonly props.

## How did you test this change?

I added a test for a store setter by path and two TODO's which address the remaining issue when setting by object.

```bash
packages/solid $ pnpm test
> Test Suites: 23 passed, 23 total
> Tests:       378 passed, 378 total
> Snapshots:   0 total
> Time:        14.132 s
> Ran all test suites.
```

### CODE REVIEW

**Comment by otonashixav** [comment]
This wrongly disallows e.g. `setStore("readonlyProp", { mutableProp: "value" })`. In the context of property getters it doesn't make sense to try and modify the return value of a getter, but it should be allowed in the case where it isn't a getter (but is still typed `readonly`).

I'm not sure if that would be enough reason to not merge though.

**Comment by JorrenH** [comment]
I updated the type-checking to be done for the store keys instead of the StoreSetter. This approach results in better developer feedback on the readonly key. I also added tests for every interface of the SetStoreFunction.

@otonashixav Fair point, and I agree with your argument. Conceptually using the merge syntax on a readonly prop doesn't make much sense to me, but it's a limitation to consider.

**Review by otonashixav — APPROVED** [review]
If the issue mentioned in my previous comment is acceptable, I am okay with these changes.

**Comment by ryansolid** [comment]
Thanks

**Pull request merged**
