### PR TITLE
improve createResource types

### PR DESCRIPTION
**Pull request by atk**
+ JSDoc comments for better IDE integration

Exporting the internal types of createResource makes extending it by tertiary primitives (e.g. https://github.com/davedbase/solid-primitives/tree/main/packages/fetch) easier.

JSDoc comments allow us to improve the developer experience by helping them directly in their IDE. To try it, hover over a function signature e.g. of `createSignal` or `createResource` in visual studio code or similarly advanced IDEs.

### CODE REVIEW

**Comment by LXSMNSYC** [comment]
- Any particular reason as to why `initialValue` has a different type from the success value?
- There's also some potential `Resource` type change to handle idle state (source = null), please check this [issue thread](https://github.com/solidjs/solid/issues/608).

**Comment by ryansolid** [comment]
I'm pretty stoked to have the JSDocs in.

TypeScript need to look at a bit more to understand. I know work was done to make sure that the type could be inferred correctly from initial value. And it's important that resources that don't start with an initial value are nullable, since it is possible for them to not have a value. That being said it going null afterwards I'm fine being explicit about in end user types and not including here as it would ever go null unless you set the source that way. But just want to ensure that is retained, the type inference and the fact when not initially set it can be nullable.

**Review by rturnq — COMMENTED** [review]
I started this review with some specific code changes in mind but after further examination it looks like these changes have regressions which could be resolved in a number of ways depending on questions like does allowing having the type `T` and `I` be different outside of the undefined `initialValue` case.

Here are a number of different cases that work as expected today. This PR causes `r2` and `r7` to fail:
```ts
const [r1] = createResource(() => Promise.resolve(1))
const [r2] = createResource(() => Promise.resolve(1), { name: 'me' })
const [r3] = createResource(() => Promise.resolve(1), { initialValue: 0 })
const [r4] = createResource(() => Promise.resolve(1), { initialValue: undefined })
const [r5] = createResource(true, () => Promise.resolve(1))
const [r6] = createResource(true, () => Promise.resolve(1), { name: 'me' })
const [r7] = createResource(true, () => Promise.resolve(1), { initialValue: 0 })
const [r8] = createResource(true, () => Promise.resolve(1), { initialValue: undefined })
```
I will add my remaining thoughts to the general comments.

**Comment by rturnq** [comment]
Looking primarily at the `createResource` type changes

- I think it makes sense to create named types for the argument and return types. Like you said this will make it easier for someone to build on top.
- I see little value in adding a second generic to `ResourceReturn` and `Resource` to specify the initial value type. In `Resource` they ultimately get combined in a union for the function return type and the individual types are never needed separately. Therefore, the upstream type user can just pass the type union in as a single generic.
- Same question as @LXSMNSYC, do we want to allow the initial value to have a different type as the fetcher return type outside of the undefined `initialValue` case?

**Comment by atk** [comment]
Thanks for your feedback. While the idea was that `I` either extends `T` or `T | undefined`, this does not seem to work as intended. I have refactored the types to fix the failing cases and removed `ResourceReturn` as you suggested.

**Comment by rturnq** [comment]
I actually thought `ResourceReturn` was fine to keep, I just wanted to remove the second generic like you have done with `Resource`. It might make sense to at codify the actions object to make it easier for things to build on top and tighten the other definitions.

```ts
interface ResourceActions<T> { mutate: Setter<T>; refetch: () => void; }
```

I think createResource can be simplified from 6 overloads down to 4 be combining the cases where `options` is defined but `initialValue` is not defined and where `options` is not defined. This means overload 1 is removed and 3 has its `options` parameter made optional with a `?`. Similarly overload 4 is removed and 6 has `options` made optional. As far as I can tell we don't lose anything by doing this.

**Comment by atk** [comment]
Thanks again for your time and your valuable feedback. I have implemented all the suggested changes. Yes, it makes sense to bundle the ResourceActions and this makes it easier to extend, too.

**Comment by atk** [comment]
I'll keep the return types as is, because you'll see easier that the result is an array then.

**Comment by rturnq** [comment]
@atk Your latest updates look good to me. Those test-cases I provided are all working as expected and the types seem succinct. From a `createResource` types standpoint, I think this is in a good state to merge now.

**Comment by LXSMNSYC** [comment]
Hmmm I was thinking, can we consider this? https://github.com/solidjs/solid/issues/608

**Comment by atk** [comment]
@LXSMNSYC let's not draw this PR out even longer, shall we? Incremental improvements is the way to go.

@rturnq We forgot about fixed generics.

**Comment by ryansolid** [comment]
Thank you so much. Thank you for all the effort put in here.

**Pull request merged**
