### PR TITLE
fix: add explicit extensions and exports fields

### PR DESCRIPTION
**Pull request by Drevoed**
## Summary

Following the trace of https://discord.com/channels/722131463138705510/783844647528955931/999968111937736764, I have found out the culprit of solid-js's problem with typescript and specifically NodeNext setting. The extensions in the .d.ts files must be defined explicitly, as well as have the correct `exports.import.types` being set. This pull request does exactly that. 

Adding extensions won't break existing typescript codebases.
See this comment: https://github.com/microsoft/TypeScript/issues/16577#issuecomment-754941937

This PR depends on: https://github.com/ryansolid/dom-expressions/pull/154
## How did you test this change?

Published a new version locally and tested pet projects using solid and checked the type output and inference of exports from 'solid-js' when using NodeNext `module` and `moduleResolution`.

### CODE REVIEW

**Comment by Drevoed** [comment]
FFS, I forgot Jest exists.

**Comment by ryansolid** [comment]
This looks good. Any chance I can get you to rebase and make the PR against `next` branch. I usually would do it myself but we just completely changed the build system and are gearing towards a new release. Probably makes sense to add module changes there

**Comment by Drevoed** [comment]
Sure, will do

**Comment by ryansolid** [comment]
Thank you.

**Pull request merged**
