### PR TITLE
Optimize `mergeProps` and `splitProps`

### PR DESCRIPTION
**Pull request by juanrgm**
## Summary

1. `Object.defineProperties` is slower than `Object.defineProperty`.
2. `Object.getOwnPropertyDescriptors` is slower than `Object.getOwnPropertyDescriptor`.
3. `Object.defineProperty` is slower than to assign a value.
4. Obviously, getter is slower than value access.

## How did you test this change?

```sh
cd packages/solid
npm t
```

```sh
FILTER=mergeProps npx vitest bench --run
```
<details>
<summary>report</summary>

```
 RUN  v0.29.3

 ✓ test/component.bench.ts  (54 tests) 31401ms


 BENCH  Summary

  mergeProps - test/component.bench.ts > mergeProps-static(5, 1)
    1.85x faster than oldMergeProps

  mergeProps - test/component.bench.ts > mergeProps-static(5, 1, 2)
    1.96x faster than oldMergeProps

  mergeProps - test/component.bench.ts > mergeProps-static(0, 15)
    1.58x faster than oldMergeProps

  mergeProps - test/component.bench.ts > mergeProps-static(0, 3, 2)
    1.86x faster than oldMergeProps

  mergeProps - test/component.bench.ts > mergeProps-static(0, 100)
    1.67x faster than oldMergeProps

  mergeProps - test/component.bench.ts > mergeProps-static(0, 100, 3, 2)
    2.03x faster than oldMergeProps

  mergeProps - test/component.bench.ts > mergeProps-static(25, 100)
    1.78x faster than oldMergeProps

  mergeProps - test/component.bench.ts > mergeProps-static(50, 100)
    1.86x faster than oldMergeProps

  mergeProps - test/component.bench.ts > mergeProps-static(100, 25)
    1.85x faster than oldMergeProps

  mergeProps - test/component.bench.ts > mergeProps-signal(5, 1)
    1.52x faster than oldMergeProps

  mergeProps - test/component.bench.ts > mergeProps-signal(5, 1, 2)
    1.65x faster than oldMergeProps

  mergeProps - test/component.bench.ts > mergeProps-signal(0, 15)
    1.51x faster than oldMergeProps

  mergeProps - test/component.bench.ts > mergeProps-signal(0, 3, 2)
    1.77x faster than oldMergeProps

  mergeProps - test/component.bench.ts > mergeProps-signal(0, 100)
    1.61x faster than oldMergeProps

  mergeProps - test/component.bench.ts > mergeProps-signal(0, 100, 3, 2)
    1.65x faster than oldMergeProps

  mergeProps - test/component.bench.ts > mergeProps-signal(25, 100)
    1.56x faster than oldMergeProps

  mergeProps - test/component.bench.ts > mergeProps-signal(50, 100)
    1.55x faster than oldMergeProps

  mergeProps - test/component.bench.ts > mergeProps-signal(100, 25)
    1.70x faster than oldMergeProps

  mergeProps - test/component.bench.ts > mergeProps-mixed(5, 1)
    1.61x faster than oldMergeProps

  mergeProps - test/component.bench.ts > mergeProps-mixed(5, 1, 2)
    1.69x faster than oldMergeProps

  mergeProps - test/component.bench.ts > mergeProps-mixed(0, 15)
    1.60x faster than oldMergeProps

  mergeProps - test/component.bench.ts > mergeProps-mixed(0, 3, 2)
    1.59x faster than oldMergeProps

  mergeProps - test/component.bench.ts > mergeProps-mixed(0, 100)
    1.55x faster than oldMergeProps

  mergeProps - test/component.bench.ts > mergeProps-mixed(0, 100, 3, 2)
    1.58x faster than oldMergeProps

  mergeProps - test/component.bench.ts > mergeProps-mixed(25, 100)
    1.62x faster than oldMergeProps

  mergeProps - test/component.bench.ts > mergeProps-mixed(50, 100)
    1.62x faster than oldMergeProps

  mergeProps - test/component.bench.ts > mergeProps-mixed(100, 25)
    1.63x faster than oldMergeProps

```
</details>

```sh
FILTER=splitProps-mixed npx vitest bench --run
```
<details>
<summary>report</summary>

```
 RUN  v0.29.3

 ✓ test/component.bench.ts  (18 tests) 13908ms


 BENCH  Summary

  splitProps - test/component.bench.ts > splitProps-mixed(5, 1)
    2.19x faster than oldSplitProps

  splitProps - test/component.bench.ts > splitProps-mixed(5, 1, 2)
    2.19x faster than oldSplitProps

  splitProps - test/component.bench.ts > splitProps-mixed(0, 15)
    4.71x faster than oldSplitProps

  splitProps - test/component.bench.ts > splitProps-mixed(0, 3, 2)
    6.65x faster than oldSplitProps

  splitProps - test/component.bench.ts > splitProps-mixed(0, 100)
    24.16x faster than oldSplitProps

  splitProps - test/component.bench.ts > splitProps-mixed(0, 100, 3, 2)
    77.38x faster than oldSplitProps

  splitProps - test/component.bench.ts > splitProps-mixed(25, 100)
    2.98x faster than oldSplitProps

  splitProps - test/component.bench.ts > splitProps-mixed(50, 100)
    2.84x faster than oldSplitProps

  splitProps - test/component.bench.ts > splitProps-mixed(100, 25)
    2.92x faster than oldSplitProps
```
</details>

```sh
FILTER=splitProps-signal npx vitest bench --run
```
<details>
<summary>report</summary>

```

 RUN  v0.29.3

 ✓ test/component.bench.ts  (18 tests) 13717ms


 BENCH  Summary

  splitProps - test/component.bench.ts > splitProps-signal(5, 1)
    1.70x faster than oldSplitProps

  splitProps - test/component.bench.ts > splitProps-signal(5, 1, 2)
    1.87x faster than oldSplitProps

  splitProps - test/component.bench.ts > splitProps-signal(0, 15)
    4.83x faster than oldSplitProps

  splitProps - test/component.bench.ts > splitProps-signal(0, 3, 2)
    6.20x faster than oldSplitProps

  splitProps - test/component.bench.ts > splitProps-signal(0, 100)
    24.08x faster than oldSplitProps

  splitProps - test/component.bench.ts > splitProps-signal(0, 100, 3, 2)
    72.55x faster than oldSplitProps

  splitProps - test/component.bench.ts > splitProps-signal(25, 100)
    2.18x faster than oldSplitProps

  splitProps - test/component.bench.ts > splitProps-signal(50, 100)
    2.04x faster than oldSplitProps

  splitProps - test/component.bench.ts > splitProps-signal(100, 25)
    2.37x faster than oldSplitProps
```
</details>

```sh
FILTER=splitProps-static npx vitest bench --run
```
<details>
<summary>report</summary>

```

 RUN  v0.29.3

 ✓ test/component.bench.ts  (18 tests) 14521ms


 BENCH  Summary

  splitProps - test/component.bench.ts > splitProps-static(5, 1)
    6.35x faster than oldSplitProps

  splitProps - test/component.bench.ts > splitProps-static(5, 1, 2)
    7.86x faster than oldSplitProps

  splitProps - test/component.bench.ts > splitProps-static(0, 15)
    4.96x faster than oldSplitProps

  splitProps - test/component.bench.ts > splitProps-static(0, 3, 2)
    6.82x faster than oldSplitProps

  splitProps - test/component.bench.ts > splitProps-static(0, 100)
    25.39x faster than oldSplitProps

  splitProps - test/component.bench.ts > splitProps-static(0, 100, 3, 2)
    77.97x faster than oldSplitProps

  splitProps - test/component.bench.ts > splitProps-static(25, 100)
    10.81x faster than oldSplitProps

  splitProps - test/component.bench.ts > splitProps-static(50, 100)
    8.31x faster than oldSplitProps

  splitProps - test/component.bench.ts > splitProps-static(100, 25)
    7.25x faster than oldSplitProps
```
</details>

### CODE REVIEW

**Comment by ryansolid** [comment]
Interesting. I didn't realize that, so getting property descriptor n times in a loop is faster than that getting all them all at once in the plural form. That's good to know.

**Comment by juanrgm** [comment]
With the latest changes the tests are successful (I still need to add more tests for `splitProps`).

Not generating breaking changes means a loss of performance, even so the improvement is noticeable (x2).

In the next merge request you can discuss which improvements to unlock (commented out in the code with `// [breaking && performance]`), that's when performance can reach x8.

<details>
<summary>report</summary>

```

 RUN  v0.29.3

 ✓ test/component.bench.ts  (54 tests) 32116ms


 BENCH  Summary

  mergeProps - test/component.bench.ts > mergeProps-static(5, 1)
    7.34x faster than oldMergeProps

  mergeProps - test/component.bench.ts > mergeProps-static(5, 1, 2)
    8.00x faster than oldMergeProps

  mergeProps - test/component.bench.ts > mergeProps-static(0, 15)
    8.78x faster than oldMergeProps

  mergeProps - test/component.bench.ts > mergeProps-static(0, 3, 2)
    6.13x faster than oldMergeProps

  mergeProps - test/component.bench.ts > mergeProps-static(0, 100)
    6.98x faster than oldMergeProps

  mergeProps - test/component.bench.ts > mergeProps-static(0, 100, 3, 2)
    6.48x faster than oldMergeProps

  mergeProps - test/component.bench.ts > mergeProps-static(25, 100)
    5.92x faster than oldMergeProps

  mergeProps - test/component.bench.ts > mergeProps-static(50, 100)
    4.73x faster than oldMergeProps

  mergeProps - test/component.bench.ts > mergeProps-static(100, 25)
    6.28x faster than oldMergeProps

  mergeProps - test/component.bench.ts > mergeProps-signal(5, 1)
    1.59x faster than oldMergeProps

  mergeProps - test/component.bench.ts > mergeProps-signal(5, 1, 2)
    1.52x faster than oldMergeProps

  mergeProps - test/component.bench.ts > mergeProps-signal(0, 15)
    1.46x faster than oldMergeProps

  mergeProps - test/component.bench.ts > mergeProps-signal(0, 3, 2)
    1.53x faster than oldMergeProps

  mergeProps - test/component.bench.ts > mergeProps-signal(0, 100)
    1.60x faster than oldMergeProps

  mergeProps - test/component.bench.ts > mergeProps-signal(0, 100, 3, 2)
    1.55x faster than oldMergeProps

  mergeProps - test/component.bench.ts > mergeProps-signal(25, 100)
    1.51x faster than oldMergeProps

  mergeProps - test/component.bench.ts > mergeProps-signal(50, 100)
    1.49x faster than oldMergeProps

  mergeProps - test/component.bench.ts > mergeProps-signal(100, 25)
    1.51x faster than oldMergeProps

  mergeProps - test/component.bench.ts > mergeProps-mixed(5, 1)
    1.88x faster than oldMergeProps

  mergeProps - test/component.bench.ts > mergeProps-mixed(5, 1, 2)
    2.40x faster than oldMergeProps

  mergeProps - test/component.bench.ts > mergeProps-mixed(0, 15)
    2.25x faster than oldMergeProps

  mergeProps - test/component.bench.ts > mergeProps-mixed(0, 3, 2)
    1.75x faster than oldMergeProps

  mergeProps - test/component.bench.ts > mergeProps-mixed(0, 100)
    2.35x faster than oldMergeProps

  mergeProps - test/component.bench.ts > mergeProps-mixed(0, 100, 3, 2)
    2.22x faster than oldMergeProps

  mergeProps - test/component.bench.ts > mergeProps-mixed(25, 100)
    2.20x faster than oldMergeProps

  mergeProps - test/component.bench.ts > mergeProps-mixed(50, 100)
    2.38x faster than oldMergeProps

  mergeProps - test/component.bench.ts > mergeProps-mixed(100, 25)
    2.27x faster than oldMergeProps
```
</details>

Before merging this branch, I'll remove the `/component.old.ts` file.

**Comment by ryansolid** [comment]
This looks good.. can you expand on the `breaking/performance` comments. I'm gathering you are saying it would be breaking but allow better performance. And breaking in what sense? Almost all the changes also reduce code so I'm definitely interested.

**Comment by juanrgm** [comment]
Uncommenting the `[breaking && performance]` lines will break the following tests in `mergeProps`:
- keeps references
- with getter keeps references
- always returns a new reference
- always returns getters
- always returns unwritables

But it will alsobincrease performance.

The conservative option it would be to not break the tests in `1.7.4` and wait for `1.8.0`. 

That tests are touching the limits and breaking them should not cause problems in the ecosystem because are undocumented features, but I don't know. What do you think?

**Comment by ryansolid** [comment]
Thanks

**Pull request merged**
