### PR TITLE
Fix createMutable to handle reactivity in case element is undefined

### PR DESCRIPTION
**Pull request by paoloricciuti**
## Summary

Fix for issue #1111 

## How did you test this change?

I was unable to run the test in local (i'll try again) but i've added a test in the test suite that should be run by the CI i guess.

### CODE REVIEW

**Comment by ryansolid** [comment]
Thank you. I know why this is failing but it does beg the question if everything goes through that check we probably don't need the signal to have the comparator and we can trim code and execution. That change has farther reaching implications. So this one might be better to merge into the next branch which I should be publishing today or tomorrow as part of pre-release for 1.5.

**Comment by paoloricciuti** [comment]
What I meant is that I was unable to run any test in local, but now I'm seeing that the CI is failing...I'll take a look and maybe go a little deeper if that's something that you are interested into fix.

**Comment by ryansolid** [comment]
It is and your fix is mostly right, but there is another change needed that I need to test repercussions on. So if you don't mind I will probably merge this as is, into next branch after I re-evaluate the other required changes.

**Comment by paoloricciuti** [comment]
You are the boss...out of curiosity: why is failing? Also...is there something I need to do to make test work locally? I had "unexpected token" errors.

**Comment by ryansolid** [comment]
Did you run `npm run build` before testing the first time?

The problem is the internal signal has a comparison function which prevents it from triggering anyway. undefined === undefined. But given we already do the equality check there I am thinking we might be able to remove the comparison function.

**Comment by paoloricciuti** [comment]
> Did you run `npm run build` before testing the first time?
> 
> The problem is the internal signal has a comparison function which prevents it from triggering anyway. undefined === undefined. But given we already do the equality check there I am thinking we might be able to remove the comparison function.

Yes I did run `npm run build` but it still gave me the error...also tu build I had to npm install into every single package.

Yeah I understand and I feel totally stupid now 😃

**Comment by ryansolid** [comment]
Thank you.

**Pull request merged**
